Support otp tokens TOOLTIME-60
seibert-media/teamvault pull request #161
Opened 2024-07-29 12:11 UTC by LefGian

Added support for One-Time-Passwords for Teamvault according to ticket [TOOLTIME-60](https://seibertmedia-cloud.atlassian.net/browse/TOOLTIME-60)

2024-08-01 14:24 UTC, MaZderMind requested changes

2024-08-01 14:24 UTC, MaZderMind commented on teamvault/apps/secrets/api/views.py
> +    # data = secret_revision.secret.get_data(request.user)
Commented Code is dead code: lieber entfernen als auskommentieren (dafür gibt's ne git history)

2024-08-01 14:24 UTC, MaZderMind commented on teamvault/apps/secrets/api/views.py
> +    else:
Ich persönlich finde es schöner das `key = None` einfach vor dem `if` zu initialisieren aber das ist vmtl. ne geschmacksfrage.

2024-08-01 14:24 UTC, MaZderMind commented on teamvault/apps/secrets/models.py
> +            if sessions_tracked == 0 or timediff >= sessions_tracked * 1800 or not get_otp_key:
Ich denke das soll verhindern, dass man bei mehrfachem lesen des selben Secrets nur einen log-Eintrag bekommt. Ich fände es schön diese Bedeutung durch eine Zwischenvariable auszudrücken und eigentlich die Logik dazu sogar komplett in eine benannte Funktion auszulagern, also sowas:
```
if not has_already_been_logged(request):
  log(…)
```

dadurch würden zum einen im Moment weit auseinande stehendenVerwendungen von `request.session["sessions_tracked"]` zusammen rutschen und zum anderen dieser Aspekt von den anderen Dingen die hier passieren (z.B. vom `or not get_otp_key`), das sonst leicht untergeht.

2024-08-01 14:24 UTC, MaZderMind commented on teamvault/apps/secrets/models.py
> +            plaintext_data = f.decrypt(self.current_revision.encrypted_data.tobytes())
Hier würde es sich anbieten `encrypted_data` in eine eigene Variable zu tun und das `f.decrypt(encrypted_data.tobytes())` dann nach dem if zu machen. Weniger noise und so.

2024-08-01 14:24 UTC, MaZderMind commented on teamvault/apps/secrets/models.py
> +    # binary field or JSON  field?
Das sollte geklärt werden vor einem Merge.

2024-08-01 14:24 UTC, MaZderMind commented on teamvault/apps/secrets/templates/secrets/addedit_content/password.html
> +                        data = data.slice(data.indexOf("secret") + 7);
Magic `7` sollte in eine Konstante oder anders berechnet werden.

2024-08-01 14:24 UTC, MaZderMind commented on teamvault/apps/secrets/templates/secrets/addedit_content/password.html
> +                    ctx.drawImage(img, 0, 0, canvas.width, canvas.height);
Wenn img einen transparenten Hintergrund hat (z.B. ein png oder gif) ist es gute Manier vorher den Canvas auf eine definierte Farbe (z.B. weiß) zu resetten. Es gibt QR-Codes die Schwarz-auf-Transparent generiert werden. siehe `fillRect()` & co.

2024-08-01 14:24 UTC, MaZderMind commented on teamvault/apps/secrets/templates/secrets/detail_content/_js.html
> +            setInterval(() => {otp.otpCountdown(countdownContainerEl, countdownNumberEl, textElement, '{{ secret_url }}', bigElement)}, 1_000);
Das würde auf 3 Zeilen lesbarer ausschauen ;)

2024-08-01 14:24 UTC, MaZderMind commented on teamvault/apps/secrets/templates/secrets/detail_content/password.html
> +                        onclick="largeType(document.getElementById('otp-field').innerHTML,
Statt `onclick` im HTML fände ich ein `addEventListener` wie du's sonst gemacht hast konsistenter (und man muss nicht so mit den Quotes aufpassen)

2024-08-01 14:24 UTC, MaZderMind commented on teamvault/apps/secrets/templates/secrets/detail_content/password.html
> +            largeTypeElement.classList.add('invisible');
Das könnte man schön zusammnfassen:
```
[largeTypeElement, largeTypePassword, …].each(el => el.classList.add('invisible'));
```

usw.

2024-08-01 14:24 UTC, MaZderMind commented on teamvault/apps/secrets/templates/secrets/detail_content/password.html
> +                largeTypeOTPCountdown.innerHTML = `${otpCountdownField}`;
Der Template-String hier ist redundant, oder?

2024-08-01 14:24 UTC, MaZderMind commented on teamvault/apps/secrets/templates/secrets/detail_content/password.html
> +            document.getElementById('copy-otp').setAttribute('on-click', 'showModal()');
Besser `addEventListener` nutzen (für beide Zeilen)

2024-08-01 14:24 UTC, MaZderMind commented on teamvault/apps/secrets/views.py
> +                digits = 8 if "digits=8" in plaintext_key_data else 6
`plaintext_key_data` ist doch ein URL-Pattern `otpauth://totp/…`, oder?
Dann würde ich mir sehr wünschen, die passenden Parsing-Routinen zu benutzen:
https://stackoverflow.com/a/21584580/1659732

2024-08-01 14:24 UTC, MaZderMind commented on teamvault/apps/secrets/views.py
> +                digits = 8 if "digits=8" in plaintext_key_data else 6
Hier wird noch mal geparst und das selbe JSON zusammengebaut wie oben -> in eine Funktion auslagern

2024-08-01 14:24 UTC, MaZderMind commented on teamvault/static/js/otp.js
> +  const response = await fetch(secret_url);
Warum holen wir das secret alle 30s noch mal ab? Das ändert sich doch nicht, oder?

Anders gefragt: Warum holen wir das secret *überhaupt* in den Browser? Ich fände es wesentlich sicherer wenn das Secret im TeamVault bleibt und nur der OTP Code an den Browser geht – dann könnte auch keiner sich das OTP Token in sein eigenes Handy kopieren.

2024-08-01 14:24 UTC, MaZderMind commented on teamvault/static/js/otp.js
> +  algortihm = secretData["algorithm"]; // TODO maybe write own version that consideres algortihm
Was passiert denn jetzt wenn ein OTP Token mit einem anderen (?) Algorithmus vorbei kommt? Sollte dann hier nicht wenigstens eine Fehlermeldung generiert werden bzw. besser beim Anlegen schon gewarnt werden, dass das nicht geht?

2024-08-01 14:24 UTC, MaZderMind commented on teamvault/static/js/otp.js
> +  const newFieldDataBig = otp.slice(0, 3) + "<span class='separator'></span>" + otp.slice(3); // without spaces between separator and OTP
Die beden Zeilen generieren doch das selbe HTML *und* sind immutable, also braucht's doch nur eine davon, oder?

2024-08-01 14:24 UTC, MaZderMind commented on teamvault/static/js/otp.js
> +    refreshOtpEvery30Sec(inputField, secret_url, bigElement).then();
Ich denke es wäre schöner auch `function otpCountdown` als async zu definieren, so dass du hier await benutzen kannst. Das Promise würde dann erst ganz am Ende, beim Call von `otpCountdown(…)` aufgelöst werden. Das ist schöner, weil man dann als caller noch was machen kann, wenn die Aktion dann tatsächlich fertig ist.

2024-08-01 14:24 UTC, MaZderMind commented on teamvault/static/js/otp.js
> +  circleElement.style.setProperty("stroke-dashoffset", progressOffset+'px');
Nett 👍

2024-08-01 14:26 UTC, MaZderMind commented
Ich hoffe es ist okay dass ich auch reviewed habe. Hauptsächlich frage ich mich, ob man überhaupt das Secret in den Browser übertragen sollte - ich fände es besser nur den generierten OTP Code zu übertragen und das Secret im Backend zu belassen.

Wenn man sich aber (ggf. zunächst) dazu entscheidet den OTP Code im Browser zu berechnen sollte man das Secret nicht alle 30s neu laden sondern nur einmal.

2024-08-20 13:13 UTC, dracador commented on teamvault/apps/secrets/models.py
> +        except ValueError:
excepting a JSONDecodeError would probably be safer here

2024-08-20 13:21 UTC, dracador commented on teamvault/apps/secrets/models.py
> +        plaintext_data_sha256 = sha256(dumps(plaintext_data).encode('utf-8')).hexdigest()
Use "else" to not waste unnecessary calls

2024-08-20 13:22 UTC, dracador commented on teamvault/apps/secrets/models.py
> +            except ValueError:
JSONDecodeError

2024-08-20 13:25 UTC, dracador commented on teamvault/apps/secrets/models.py
> +            old_data = f.decrypt(self.current_revision.encrypted_data.tobytes()).decode('utf-8')
Put a comment here why we need those conversions of strings to dicts

2024-08-20 13:30 UTC, dracador commented on teamvault/apps/secrets/models.py
> +                    plaintext_data[key] = old_data.get(key)
Don't use .get() since you don't want to save None values

2024-08-20 13:43 UTC, dracador commented on teamvault/apps/secrets/templates/secrets/addedit_content/password.html
> +                        data = data.slice(data.indexOf("secret") + 7);
If the data is always a valid URL, you could access individual fields like this:

```javascript
let secret_url = new URL(data)
data = secret_url.searchParams.get('secret')
```

2024-08-21 12:39 UTC, dracador requested changes

2024-08-21 12:39 UTC, dracador commented on teamvault/apps/secrets/templates/secrets/detail_content/_js.html
> +                console.log(otpValue);
remove log

2024-08-21 12:39 UTC, dracador commented on teamvault/apps/secrets/templates/secrets/detail_content/password.html
> +                                 largeTypeElement);
indentation

2024-08-21 12:39 UTC, dracador commented on teamvault/apps/secrets/utils.py
> +                                        plaintext_key_data.index("&")
This will break if the URL parameters are in a different order. Better to just save the whole dict/JSON and read individual values here

2024-08-21 12:39 UTC, dracador commented on teamvault/apps/secrets/views.py
> +        context['current_revision'] = self.get_object().current_revision
Use self.object here, since self.object is a cached_property. Otherwise you'd do another database call on every self.get_object()

2024-08-21 12:39 UTC, dracador commented on teamvault/apps/secrets/views.py
> +        self.request.session['otp_key'] = None
This would cause a database insert (because we're using the default configuration for SessionMiddleware) on every single call of this view. Use session.get('otp_key') instead, when you're trying to read it

2024-08-21 12:39 UTC, dracador commented on teamvault/static/js/index.js
> +window.qrScanner = require("jsqr")
newline after

2024-08-21 12:39 UTC, dracador commented on teamvault/static/js/otp.js
> +    newFieldData = newFieldData.replace('mx-1', 'mx-3')
Just checking - there's a line that looks a lot like this one:
https://github.com/seibert-media/teamvault/pull/161/files#diff-6af8bc47ab32b99a91feaece59434c3c5de8f73169443b49100f72d7d4dba4f2R145
Is it possible to merge this or maybe add a comment on why it's duplicated

2024-08-21 12:39 UTC, dracador commented on teamvault/static/js/otp.js
> +    bigCountdownNumberElement.textContent = countdowmTime;
countdowmTime vs countdownTime

2024-08-21 12:39 UTC, dracador commented on teamvault/static/scss/circularProgressbar.scss
> +.separator {
.seperator can move into base.scss

2024-09-12 08:56 UTC, MaZderMind commented
What's the state here? We would really love to have that feature <3 Thank you!

2024-10-02 12:36 UTC, dracador requested changes

2024-10-02 12:36 UTC, dracador commented on teamvault/static/scss/base.scss
> +      background-color: var(--bs-gray-100);
This breaks the background color for other fields (like the login) after having a dark mode.
Is there any way we can make this one more specific to where it's needed?

2024-10-02 12:36 UTC, dracador commented on teamvault/apps/secrets/utils.py
> +def serialize_add_edit_data(cleaned_data, secret):
Is there any way to make this function part of either the SecretForm or the Secret model? 
I'm thinking like how it would look with a Pydantic model and getting the "correct" clieaned_data via PydanticModel.model_dump().

2024-10-02 12:36 UTC, dracador commented on teamvault/apps/secrets/utils.py
> +        secret.save()
The function name is "serialize" and password & credit card data is serialized and returned as plaintext, but this is already saved

2024-10-04 08:18 UTC, LefGian commented on teamvault/static/scss/base.scss
> +      background-color: var(--bs-gray-100);
This seems to be a change you made. I don't know which use case this serves, or if it can be made more specific.

2024-10-04 13:01 UTC, LefGian commented on teamvault/static/scss/base.scss
> +      background-color: var(--bs-gray-100);
Tried to fix it

2024-11-14 12:13 UTC, dracador approved these changes

2024-11-14 12:13 UTC, merged